import warnings
warnings.filterwarnings('ignore')

#from create_model import prepareData


from flask import Flask
from flask_restx import Api, Resource, fields

import pandas as pd
import xgboost as xgb
from sklearn.preprocessing import OneHotEncoder
import joblib

# Función para importar el modelo y predecir
predictors = predictors = ['Make_Model_Acura_MDXAWD',
 'Make_Model_Acura_RDXAWD',
 'Make_Model_Acura_RDXFWD',
 'Make_Model_Acura_TL4dr',
 'Make_Model_Acura_TLAutomatic',
 'Make_Model_Acura_TSXAutomatic',
 'Make_Model_Audi_A34dr',
 'Make_Model_Audi_A44dr',
 'Make_Model_Audi_A64dr',
 'Make_Model_Audi_A8',
 'Make_Model_Audi_Q5quattro',
 'Make_Model_Audi_Q7quattro',
 'Make_Model_Audi_S44dr',
 'Make_Model_Audi_TT2dr',
 'Make_Model_BMW_1',
 'Make_Model_BMW_3',
 'Make_Model_BMW_5',
 'Make_Model_BMW_6',
 'Make_Model_BMW_7',
 'Make_Model_BMW_X1xDrive28i',
 'Make_Model_BMW_X3AWD',
 'Make_Model_BMW_X3xDrive28i',
 'Make_Model_BMW_X5AWD',
 'Make_Model_BMW_X5xDrive35i',
 'Make_Model_Bentley_Continental',
 'Make_Model_Buick_EnclaveConvenience',
 'Make_Model_Buick_EnclaveLeather',
 'Make_Model_Buick_EnclavePremium',
 'Make_Model_Buick_LaCrosse4dr',
 'Make_Model_Buick_LaCrosseAWD',
 'Make_Model_Buick_LaCrosseFWD',
 'Make_Model_Buick_Lucerne4dr',
 'Make_Model_Buick_Regal4dr',
 'Make_Model_Buick_RegalGS',
 'Make_Model_Buick_RegalPremium',
 'Make_Model_Buick_RegalTurbo',
 'Make_Model_Cadillac_CTS',
 'Make_Model_Cadillac_CTS-V',
 'Make_Model_Cadillac_CTS4dr',
 'Make_Model_Cadillac_DTS4dr',
 'Make_Model_Cadillac_Escalade',
 'Make_Model_Cadillac_Escalade2WD',
 'Make_Model_Cadillac_Escalade4dr',
 'Make_Model_Cadillac_EscaladeAWD',
 'Make_Model_Cadillac_SRXLuxury',
 'Make_Model_Cadillac_STS4dr',
 'Make_Model_Chevrolet_Avalanche2WD',
 'Make_Model_Chevrolet_Avalanche4WD',
 'Make_Model_Chevrolet_Camaro2dr',
 'Make_Model_Chevrolet_CamaroConvertible',
 'Make_Model_Chevrolet_CamaroCoupe',
 'Make_Model_Chevrolet_Cobalt2dr',
 'Make_Model_Chevrolet_Cobalt4dr',
 'Make_Model_Chevrolet_Colorado2WD',
 'Make_Model_Chevrolet_Colorado4WD',
 'Make_Model_Chevrolet_ColoradoCrew',
 'Make_Model_Chevrolet_ColoradoExtended',
 'Make_Model_Chevrolet_Corvette2dr',
 'Make_Model_Chevrolet_CorvetteConvertible',
 'Make_Model_Chevrolet_CorvetteCoupe',
 'Make_Model_Chevrolet_CruzeLT',
 'Make_Model_Chevrolet_CruzeSedan',
 'Make_Model_Chevrolet_EquinoxAWD',
 'Make_Model_Chevrolet_EquinoxFWD',
 'Make_Model_Chevrolet_Express',
 'Make_Model_Chevrolet_Impala4dr',
 'Make_Model_Chevrolet_ImpalaLS',
 'Make_Model_Chevrolet_ImpalaLT',
 'Make_Model_Chevrolet_Malibu',
 'Make_Model_Chevrolet_Malibu1LT',
 'Make_Model_Chevrolet_Malibu4dr',
 'Make_Model_Chevrolet_MalibuLS',
 'Make_Model_Chevrolet_MalibuLT',
 'Make_Model_Chevrolet_Monte',
 'Make_Model_Chevrolet_New',
 'Make_Model_Chevrolet_Silverado',
 'Make_Model_Chevrolet_SonicHatch',
 'Make_Model_Chevrolet_SonicSedan',
 'Make_Model_Chevrolet_Suburban2WD',
 'Make_Model_Chevrolet_Suburban4WD',
 'Make_Model_Chevrolet_Suburban4dr',
 'Make_Model_Chevrolet_Tahoe2WD',
 'Make_Model_Chevrolet_Tahoe4WD',
 'Make_Model_Chevrolet_Tahoe4dr',
 'Make_Model_Chevrolet_TahoeLS',
 'Make_Model_Chevrolet_TahoeLT',
 'Make_Model_Chevrolet_TraverseAWD',
 'Make_Model_Chevrolet_TraverseFWD',
 'Make_Model_Chrysler_200LX',
 'Make_Model_Chrysler_200Limited',
 'Make_Model_Chrysler_200S',
 'Make_Model_Chrysler_200Touring',
 'Make_Model_Chrysler_300300C',
 'Make_Model_Chrysler_300300S',
 'Make_Model_Chrysler_3004dr',
 'Make_Model_Chrysler_300Base',
 'Make_Model_Chrysler_300Limited',
 'Make_Model_Chrysler_300Touring',
 'Make_Model_Chrysler_PT',
 'Make_Model_Chrysler_PacificaLimited',
 'Make_Model_Chrysler_PacificaTouring',
 'Make_Model_Chrysler_Town',
 'Make_Model_Dodge_Caliber4dr',
 'Make_Model_Dodge_Challenger2dr',
 'Make_Model_Dodge_ChallengerR/T',
 'Make_Model_Dodge_Charger4dr',
 'Make_Model_Dodge_ChargerSE',
 'Make_Model_Dodge_ChargerSXT',
 'Make_Model_Dodge_Dakota2WD',
 'Make_Model_Dodge_Dakota4WD',
 'Make_Model_Dodge_Durango2WD',
 'Make_Model_Dodge_Durango4dr',
 'Make_Model_Dodge_DurangoAWD',
 'Make_Model_Dodge_DurangoSXT',
 'Make_Model_Dodge_Grand',
 'Make_Model_Dodge_JourneyAWD',
 'Make_Model_Dodge_JourneyFWD',
 'Make_Model_Dodge_JourneySXT',
 'Make_Model_Dodge_Ram',
 'Make_Model_Dodge_Sprinter',
 'Make_Model_FIAT_500Pop',
 'Make_Model_Ford_Econoline',
 'Make_Model_Ford_EdgeLimited',
 'Make_Model_Ford_EdgeSE',
 'Make_Model_Ford_EdgeSEL',
 'Make_Model_Ford_EdgeSport',
 'Make_Model_Ford_Escape4WD',
 'Make_Model_Ford_Escape4dr',
 'Make_Model_Ford_EscapeFWD',
 'Make_Model_Ford_EscapeLImited',
 'Make_Model_Ford_EscapeLimited',
 'Make_Model_Ford_EscapeS',
 'Make_Model_Ford_EscapeSE',
 'Make_Model_Ford_EscapeXLT',
 'Make_Model_Ford_Excursion137"',
 'Make_Model_Ford_Expedition',
 'Make_Model_Ford_Expedition2WD',
 'Make_Model_Ford_Expedition4WD',
 'Make_Model_Ford_ExpeditionLimited',
 'Make_Model_Ford_ExpeditionXLT',
 'Make_Model_Ford_Explorer',
 'Make_Model_Ford_Explorer4WD',
 'Make_Model_Ford_Explorer4dr',
 'Make_Model_Ford_ExplorerBase',
 'Make_Model_Ford_ExplorerEddie',
 'Make_Model_Ford_ExplorerFWD',
 'Make_Model_Ford_ExplorerLimited',
 'Make_Model_Ford_ExplorerXLT',
 'Make_Model_Ford_F-1502WD',
 'Make_Model_Ford_F-1504WD',
 'Make_Model_Ford_F-150FX2',
 'Make_Model_Ford_F-150FX4',
 'Make_Model_Ford_F-150King',
 'Make_Model_Ford_F-150Lariat',
 'Make_Model_Ford_F-150Limited',
 'Make_Model_Ford_F-150Platinum',
 'Make_Model_Ford_F-150STX',
 'Make_Model_Ford_F-150SuperCrew',
 'Make_Model_Ford_F-150XL',
 'Make_Model_Ford_F-150XLT',
 'Make_Model_Ford_F-250King',
 'Make_Model_Ford_F-250Lariat',
 'Make_Model_Ford_F-250XL',
 'Make_Model_Ford_F-250XLT',
 'Make_Model_Ford_F-350King',
 'Make_Model_Ford_F-350Lariat',
 'Make_Model_Ford_F-350XL',
 'Make_Model_Ford_F-350XLT',
 'Make_Model_Ford_FiestaS',
 'Make_Model_Ford_FiestaSE',
 'Make_Model_Ford_FlexLimited',
 'Make_Model_Ford_FlexSE',
 'Make_Model_Ford_FlexSEL',
 'Make_Model_Ford_Focus4dr',
 'Make_Model_Ford_Focus5dr',
 'Make_Model_Ford_FocusS',
 'Make_Model_Ford_FocusSE',
 'Make_Model_Ford_FocusSEL',
 'Make_Model_Ford_FocusST',
 'Make_Model_Ford_FocusTitanium',
 'Make_Model_Ford_Fusion4dr',
 'Make_Model_Ford_FusionHybrid',
 'Make_Model_Ford_FusionS',
 'Make_Model_Ford_FusionSE',
 'Make_Model_Ford_FusionSEL',
 'Make_Model_Ford_Mustang2dr',
 'Make_Model_Ford_MustangBase',
 'Make_Model_Ford_MustangDeluxe',
 'Make_Model_Ford_MustangGT',
 'Make_Model_Ford_MustangPremium',
 'Make_Model_Ford_MustangShelby',
 'Make_Model_Ford_Ranger2WD',
 'Make_Model_Ford_Ranger4WD',
 'Make_Model_Ford_RangerSuperCab',
 'Make_Model_Ford_Super',
 'Make_Model_Ford_Taurus4dr',
 'Make_Model_Ford_TaurusLimited',
 'Make_Model_Ford_TaurusSE',
 'Make_Model_Ford_TaurusSEL',
 'Make_Model_Ford_TaurusSHO',
 'Make_Model_Ford_Transit',
 'Make_Model_Freightliner_Sprinter',
 'Make_Model_GMC_AcadiaAWD',
 'Make_Model_GMC_AcadiaFWD',
 'Make_Model_GMC_Canyon2WD',
 'Make_Model_GMC_Canyon4WD',
 'Make_Model_GMC_CanyonCrew',
 'Make_Model_GMC_CanyonExtended',
 'Make_Model_GMC_New',
 'Make_Model_GMC_Savana',
 'Make_Model_GMC_Sierra',
 'Make_Model_GMC_TerrainAWD',
 'Make_Model_GMC_TerrainFWD',
 'Make_Model_GMC_Yukon',
 'Make_Model_GMC_Yukon2WD',
 'Make_Model_GMC_Yukon4WD',
 'Make_Model_GMC_Yukon4dr',
 'Make_Model_Honda_Accord',
 'Make_Model_Honda_AccordEX',
 'Make_Model_Honda_AccordEX-L',
 'Make_Model_Honda_AccordLX',
 'Make_Model_Honda_AccordLX-S',
 'Make_Model_Honda_AccordSE',
 'Make_Model_Honda_CR-V2WD',
 'Make_Model_Honda_CR-V4WD',
 'Make_Model_Honda_CR-VEX',
 'Make_Model_Honda_CR-VEX-L',
 'Make_Model_Honda_CR-VLX',
 'Make_Model_Honda_CR-VSE',
 'Make_Model_Honda_CR-ZEX',
 'Make_Model_Honda_Civic',
 'Make_Model_Honda_CivicEX',
 'Make_Model_Honda_CivicEX-L',
 'Make_Model_Honda_CivicLX',
 'Make_Model_Honda_CivicSi',
 'Make_Model_Honda_Element2WD',
 'Make_Model_Honda_Element4WD',
 'Make_Model_Honda_FitSport',
 'Make_Model_Honda_OdysseyEX',
 'Make_Model_Honda_OdysseyEX-L',
 'Make_Model_Honda_OdysseyLX',
 'Make_Model_Honda_OdysseyTouring',
 'Make_Model_Honda_Pilot2WD',
 'Make_Model_Honda_Pilot4WD',
 'Make_Model_Honda_PilotEX',
 'Make_Model_Honda_PilotEX-L',
 'Make_Model_Honda_PilotLX',
 'Make_Model_Honda_PilotSE',
 'Make_Model_Honda_PilotTouring',
 'Make_Model_Honda_RidgelineRTL',
 'Make_Model_Honda_RidgelineSport',
 'Make_Model_Honda_S2000Manual',
 'Make_Model_Hyundai_Accent4dr',
 'Make_Model_Hyundai_Azera4dr',
 'Make_Model_Hyundai_Elantra',
 'Make_Model_Hyundai_Elantra4dr',
 'Make_Model_Hyundai_ElantraLimited',
 'Make_Model_Hyundai_Genesis',
 'Make_Model_Hyundai_Santa',
 'Make_Model_Hyundai_Sonata4dr',
 'Make_Model_Hyundai_SonataLimited',
 'Make_Model_Hyundai_SonataSE',
 'Make_Model_Hyundai_TucsonAWD',
 'Make_Model_Hyundai_TucsonFWD',
 'Make_Model_Hyundai_TucsonLimited',
 'Make_Model_Hyundai_VeracruzAWD',
 'Make_Model_Hyundai_VeracruzFWD',
 'Make_Model_INFINITI_FX35AWD',
 'Make_Model_INFINITI_G35',
 'Make_Model_INFINITI_G37',
 'Make_Model_INFINITI_QX562WD',
 'Make_Model_INFINITI_QX564WD',
 'Make_Model_Jaguar_XF4dr',
 'Make_Model_Jaguar_XJ4dr',
 'Make_Model_Jaguar_XK2dr',
 'Make_Model_Jeep_CherokeeLimited',
 'Make_Model_Jeep_CherokeeSport',
 'Make_Model_Jeep_Compass4WD',
 'Make_Model_Jeep_CompassLatitude',
 'Make_Model_Jeep_CompassLimited',
 'Make_Model_Jeep_CompassSport',
 'Make_Model_Jeep_Grand',
 'Make_Model_Jeep_Liberty4WD',
 'Make_Model_Jeep_LibertyLimited',
 'Make_Model_Jeep_LibertySport',
 'Make_Model_Jeep_Patriot4WD',
 'Make_Model_Jeep_PatriotLatitude',
 'Make_Model_Jeep_PatriotLimited',
 'Make_Model_Jeep_PatriotSport',
 'Make_Model_Jeep_Wrangler',
 'Make_Model_Jeep_Wrangler2dr',
 'Make_Model_Jeep_Wrangler4WD',
 'Make_Model_Jeep_WranglerRubicon',
 'Make_Model_Jeep_WranglerSahara',
 'Make_Model_Jeep_WranglerSport',
 'Make_Model_Jeep_WranglerX',
 'Make_Model_Kia_Forte',
 'Make_Model_Kia_ForteEX',
 'Make_Model_Kia_ForteLX',
 'Make_Model_Kia_ForteSX',
 'Make_Model_Kia_Optima4dr',
 'Make_Model_Kia_OptimaEX',
 'Make_Model_Kia_OptimaLX',
 'Make_Model_Kia_OptimaSX',
 'Make_Model_Kia_RioLX',
 'Make_Model_Kia_Sedona4dr',
 'Make_Model_Kia_SedonaEX',
 'Make_Model_Kia_SedonaLX',
 'Make_Model_Kia_Sorento2WD',
 'Make_Model_Kia_SorentoEX',
 'Make_Model_Kia_SorentoLX',
 'Make_Model_Kia_SorentoSX',
 'Make_Model_Kia_Soul+',
 'Make_Model_Kia_SoulBase',
 'Make_Model_Kia_Sportage2WD',
 'Make_Model_Kia_SportageAWD',
 'Make_Model_Kia_SportageEX',
 'Make_Model_Kia_SportageLX',
 'Make_Model_Kia_SportageSX',
 'Make_Model_Land_Rover',
 'Make_Model_Lexus_CT',
 'Make_Model_Lexus_CTCT',
 'Make_Model_Lexus_ES',
 'Make_Model_Lexus_ESES',
 'Make_Model_Lexus_GS',
 'Make_Model_Lexus_GSGS',
 'Make_Model_Lexus_GX',
 'Make_Model_Lexus_GXGX',
 'Make_Model_Lexus_IS',
 'Make_Model_Lexus_ISIS',
 'Make_Model_Lexus_LS',
 'Make_Model_Lexus_LSLS',
 'Make_Model_Lexus_LX',
 'Make_Model_Lexus_LXLX',
 'Make_Model_Lexus_RX',
 'Make_Model_Lexus_RXRX',
 'Make_Model_Lexus_SC',
 'Make_Model_Lincoln_MKXAWD',
 'Make_Model_Lincoln_MKXFWD',
 'Make_Model_Lincoln_MKZ4dr',
 'Make_Model_Lincoln_Navigator',
 'Make_Model_Lincoln_Navigator2WD',
 'Make_Model_Lincoln_Navigator4WD',
 'Make_Model_Lincoln_Navigator4dr',
 'Make_Model_Lincoln_Town',
 'Make_Model_MINI_Cooper',
 'Make_Model_Mazda_CX-7FWD',
 'Make_Model_Mazda_CX-9AWD',
 'Make_Model_Mazda_CX-9FWD',
 'Make_Model_Mazda_CX-9Grand',
 'Make_Model_Mazda_CX-9Touring',
 'Make_Model_Mazda_MX5',
 'Make_Model_Mazda_Mazda34dr',
 'Make_Model_Mazda_Mazda35dr',
 'Make_Model_Mazda_Mazda64dr',
 'Make_Model_Mazda_RX-84dr',
 'Make_Model_Mercedes-Benz_C-Class4dr',
 'Make_Model_Mercedes-Benz_C-ClassC',
 'Make_Model_Mercedes-Benz_C-ClassC300',
 'Make_Model_Mercedes-Benz_C-ClassC350',
 'Make_Model_Mercedes-Benz_E-ClassE',
 'Make_Model_Mercedes-Benz_E-ClassE320',
 'Make_Model_Mercedes-Benz_E-ClassE350',
 'Make_Model_Mercedes-Benz_M-ClassML350',
 'Make_Model_Mercedes-Benz_SL-ClassSL500',
 'Make_Model_Mercedes-Benz_SLK-ClassSLK350',
 'Make_Model_Mercedes-Benz_Sprinter',
 'Make_Model_Mercury_Grand',
 'Make_Model_Mercury_Milan4dr',
 'Make_Model_Mitsubishi_Eclipse3dr',
 'Make_Model_Mitsubishi_Galant4dr',
 'Make_Model_Mitsubishi_Lancer4dr',
 'Make_Model_Mitsubishi_Outlander',
 'Make_Model_Mitsubishi_Outlander2WD',
 'Make_Model_Mitsubishi_Outlander4WD',
 'Make_Model_Nissan_350Z2dr',
 'Make_Model_Nissan_Altima4dr',
 'Make_Model_Nissan_Armada2WD',
 'Make_Model_Nissan_Armada4WD',
 'Make_Model_Nissan_Frontier',
 'Make_Model_Nissan_Frontier2WD',
 'Make_Model_Nissan_Frontier4WD',
 'Make_Model_Nissan_Maxima4dr',
 'Make_Model_Nissan_Murano2WD',
 'Make_Model_Nissan_MuranoAWD',
 'Make_Model_Nissan_MuranoS',
 'Make_Model_Nissan_Pathfinder2WD',
 'Make_Model_Nissan_Pathfinder4WD',
 'Make_Model_Nissan_PathfinderS',
 'Make_Model_Nissan_PathfinderSE',
 'Make_Model_Nissan_Quest4dr',
 'Make_Model_Nissan_RogueFWD',
 'Make_Model_Nissan_Sentra4dr',
 'Make_Model_Nissan_Titan',
 'Make_Model_Nissan_Titan2WD',
 'Make_Model_Nissan_Titan4WD',
 'Make_Model_Nissan_Versa4dr',
 'Make_Model_Nissan_Versa5dr',
 'Make_Model_Nissan_Xterra2WD',
 'Make_Model_Nissan_Xterra4WD',
 'Make_Model_Nissan_Xterra4dr',
 'Make_Model_Pontiac_G64dr',
 'Make_Model_Pontiac_Grand',
 'Make_Model_Pontiac_Vibe4dr',
 'Make_Model_Porsche_911',
 'Make_Model_Porsche_9112dr',
 'Make_Model_Porsche_Boxster2dr',
 'Make_Model_Porsche_CayenneAWD',
 'Make_Model_Porsche_Cayman2dr',
 'Make_Model_Ram_15002WD',
 'Make_Model_Ram_15004WD',
 'Make_Model_Ram_1500Laramie',
 'Make_Model_Ram_1500Tradesman',
 'Make_Model_Ram_25002WD',
 'Make_Model_Ram_25004WD',
 'Make_Model_Ram_35004WD',
 'Make_Model_Ram_Dakota2WD',
 'Make_Model_Ram_Dakota4WD',
 'Make_Model_Scion_tC2dr',
 'Make_Model_Scion_xB5dr',
 'Make_Model_Scion_xD5dr',
 'Make_Model_Subaru_Forester2.5X',
 'Make_Model_Subaru_Forester4dr',
 'Make_Model_Subaru_Impreza',
 'Make_Model_Subaru_Impreza2.0i',
 'Make_Model_Subaru_ImprezaSport',
 'Make_Model_Subaru_Legacy',
 'Make_Model_Subaru_Legacy2.5i',
 'Make_Model_Subaru_Legacy3.6R',
 'Make_Model_Subaru_Outback2.5i',
 'Make_Model_Subaru_Outback3.6R',
 'Make_Model_Subaru_WRXBase',
 'Make_Model_Subaru_WRXLimited',
 'Make_Model_Subaru_WRXPremium',
 'Make_Model_Subaru_WRXSTI',
 'Make_Model_Suzuki_Grand',
 'Make_Model_Tesla_Model',
 'Make_Model_Toyota_4Runner2WD',
 'Make_Model_Toyota_4Runner4WD',
 'Make_Model_Toyota_4Runner4dr',
 'Make_Model_Toyota_4RunnerLimited',
 'Make_Model_Toyota_4RunnerRWD',
 'Make_Model_Toyota_4RunnerSR5',
 'Make_Model_Toyota_4RunnerTrail',
 'Make_Model_Toyota_Avalon4dr',
 'Make_Model_Toyota_AvalonLimited',
 'Make_Model_Toyota_AvalonTouring',
 'Make_Model_Toyota_AvalonXLE',
 'Make_Model_Toyota_Camry',
 'Make_Model_Toyota_Camry4dr',
 'Make_Model_Toyota_CamryBase',
 'Make_Model_Toyota_CamryL',
 'Make_Model_Toyota_CamryLE',
 'Make_Model_Toyota_CamrySE',
 'Make_Model_Toyota_CamryXLE',
 'Make_Model_Toyota_Corolla4dr',
 'Make_Model_Toyota_CorollaL',
 'Make_Model_Toyota_CorollaLE',
 'Make_Model_Toyota_CorollaS',
 'Make_Model_Toyota_FJ',
 'Make_Model_Toyota_Highlander',
 'Make_Model_Toyota_Highlander4WD',
 'Make_Model_Toyota_Highlander4dr',
 'Make_Model_Toyota_HighlanderBase',
 'Make_Model_Toyota_HighlanderFWD',
 'Make_Model_Toyota_HighlanderLimited',
 'Make_Model_Toyota_HighlanderSE',
 'Make_Model_Toyota_Land',
 'Make_Model_Toyota_Matrix5dr',
 'Make_Model_Toyota_Prius',
 'Make_Model_Toyota_Prius5dr',
 'Make_Model_Toyota_PriusBase',
 'Make_Model_Toyota_PriusFive',
 'Make_Model_Toyota_PriusFour',
 'Make_Model_Toyota_PriusOne',
 'Make_Model_Toyota_PriusThree',
 'Make_Model_Toyota_PriusTwo',
 'Make_Model_Toyota_RAV4',
 'Make_Model_Toyota_RAV44WD',
 'Make_Model_Toyota_RAV44dr',
 'Make_Model_Toyota_RAV4Base',
 'Make_Model_Toyota_RAV4FWD',
 'Make_Model_Toyota_RAV4LE',
 'Make_Model_Toyota_RAV4Limited',
 'Make_Model_Toyota_RAV4Sport',
 'Make_Model_Toyota_RAV4XLE',
 'Make_Model_Toyota_Sequoia4WD',
 'Make_Model_Toyota_Sequoia4dr',
 'Make_Model_Toyota_SequoiaLimited',
 'Make_Model_Toyota_SequoiaPlatinum',
 'Make_Model_Toyota_SequoiaSR5',
 'Make_Model_Toyota_Sienna5dr',
 'Make_Model_Toyota_SiennaLE',
 'Make_Model_Toyota_SiennaLimited',
 'Make_Model_Toyota_SiennaSE',
 'Make_Model_Toyota_SiennaXLE',
 'Make_Model_Toyota_Tacoma2WD',
 'Make_Model_Toyota_Tacoma4WD',
 'Make_Model_Toyota_TacomaBase',
 'Make_Model_Toyota_TacomaPreRunner',
 'Make_Model_Toyota_Tundra',
 'Make_Model_Toyota_Tundra2WD',
 'Make_Model_Toyota_Tundra4WD',
 'Make_Model_Toyota_TundraBase',
 'Make_Model_Toyota_TundraLimited',
 'Make_Model_Toyota_TundraSR5',
 'Make_Model_Toyota_Yaris',
 'Make_Model_Toyota_Yaris4dr',
 'Make_Model_Toyota_YarisBase',
 'Make_Model_Toyota_YarisLE',
 'Make_Model_Volkswagen_CC4dr',
 'Make_Model_Volkswagen_Eos2dr',
 'Make_Model_Volkswagen_GLI4dr',
 'Make_Model_Volkswagen_GTI2dr',
 'Make_Model_Volkswagen_GTI4dr',
 'Make_Model_Volkswagen_Golf',
 'Make_Model_Volkswagen_Jetta',
 'Make_Model_Volkswagen_New',
 'Make_Model_Volkswagen_Passat',
 'Make_Model_Volkswagen_Passat4dr',
 'Make_Model_Volkswagen_Tiguan2WD',
 'Make_Model_Volkswagen_TiguanS',
 'Make_Model_Volkswagen_TiguanSE',
 'Make_Model_Volkswagen_TiguanSEL',
 'Make_Model_Volkswagen_Touareg4dr',
 'Make_Model_Volvo_C702dr',
 'Make_Model_Volvo_S60T5',
 'Make_Model_Volvo_S804dr',
 'Make_Model_Volvo_XC60AWD',
 'Make_Model_Volvo_XC60FWD',
 'Make_Model_Volvo_XC60T6',
 'Make_Model_Volvo_XC704dr',
 'Make_Model_Volvo_XC90AWD',
 'Make_Model_Volvo_XC90FWD',
 'Make_Model_Volvo_XC90T6',
 'Mileage',
 'State_ AL',
 'State_ AR',
 'State_ AZ',
 'State_ CA',
 'State_ CO',
 'State_ CT',
 'State_ DC',
 'State_ DE',
 'State_ FL',
 'State_ GA',
 'State_ HI',
 'State_ IA',
 'State_ ID',
 'State_ IL',
 'State_ IN',
 'State_ KS',
 'State_ KY',
 'State_ LA',
 'State_ MA',
 'State_ MD',
 'State_ ME',
 'State_ MI',
 'State_ MN',
 'State_ MO',
 'State_ MS',
 'State_ MT',
 'State_ NC',
 'State_ ND',
 'State_ NE',
 'State_ NH',
 'State_ NJ',
 'State_ NM',
 'State_ NV',
 'State_ NY',
 'State_ OH',
 'State_ OK',
 'State_ OR',
 'State_ PA',
 'State_ RI',
 'State_ SC',
 'State_ SD',
 'State_ TN',
 'State_ TX',
 'State_ UT',
 'State_ VA',
 'State_ VT',
 'State_ WA',
 'State_ WI',
 'State_ WV',
 'State_ WY',
 'Year']



def prepareData (df, isTesting=False, colsList=[]):
    # Concatenar las variables Make y Model
    df['Make_Model']=df['Make']+'_'+df['Model'] 

    # Crear la lista de variables según el conjunto de datos que se esta transformando
    if isTesting == False:
        varList1 = ['Price', 'Year', 'Mileage', 'State', 'Make_Model']
        varList2 = ['Price', 'Year', 'Mileage']
    else:
        varList1 = ['Year', 'Mileage', 'State', 'Make_Model']
        varList2 = ['Year', 'Mileage']

    # Filtrar el dataframe por las columnas de interes
    df = df[varList1]
    
    # Crear la instancia de OneHotEncoder y las columnas dummy para State y Make_Model
    encoder = OneHotEncoder(drop='first', sparse=False) # Usamos drop=’first’ para eliminar la primera categoría en cada característica
    colsToEncoded=['State', 'Make_Model']
    dfCoded = pd.DataFrame(encoder.fit_transform(df[colsToEncoded]))
    # nombrar las columnas dummy
    dfCoded.columns = encoder.get_feature_names_out(colsToEncoded)
    # agregar las columnas 'Year', 'Mileage' o 'Price', 'Year', 'Mileage' según corresponda al conjunto de datos
    dfCoded[varList2]=df[varList2]

    if isTesting==True:
        columnas_faltantes = set(colsList) - set(dfCoded.columns)
        for columna in columnas_faltantes:
            dfCoded[columna] = 0
    
    dfCoded = dfCoded.sort_index(axis=1)
    return dfCoded

def usedCarPricesPredict(Year, Mileage, State, Make, Model):
    clf = joblib.load('usedCarPrices.pkl') 
    data_ = pd.DataFrame({'Year': [Year], 'Mileage': [Mileage], 'State': [State], 'Make': [Make], 'Model': [Model]})
    X_Test = prepareData(data_, True, predictors)
    # Make prediction
    p1 = clf.predict(X_Test)
    return p1

# Predicción de probabilidad de que un link sea phishing
#usedCarPricesPredict(2014, 31909, 'MD', 'Nissan', 'MuranoAWD')


# Predicción de probabilidad de que un link sea phishing
#usedCarPricesPredict(2017, 5362, 'FL', 'Jeep', 'Wrangle')

# Definición aplicación Flask
app = Flask(__name__)

# Definición API Flask
api = Api(
    app, 
    version='1.0', 
    title='Used Car Price Prediction API',
    description='used car price prediction API')

ns = api.namespace('predict', 
     description='price prediction')

# Definición argumentos o parámetros de la API
parser = api.parser()
parser.add_argument(
    'Year', 
    type=int, 
    required=True, 
    help='year of manufacture', 
    location='args')

parser.add_argument(
    'Mileage', 
    type=float, 
    required=True, 
    help='vehicle mileage', 
    location='args')

parser.add_argument(
    'State', 
    type=str, 
    required=True, 
    help='Abbreviation of US state names', 
    location='args')

parser.add_argument(
    'Make', 
    type=str, 
    required=True, 
    help='vehicle manufacturer', 
    location='args')

parser.add_argument(
    'Model', 
    type=str, 
    required=True, 
    help='vehicle model', 
    location='args')

resource_fields = api.model('Resource', {
    'result': fields.String,
})


# Definición de la clase para disponibilización
@ns.route('/')
class UsedCarPricePredictionAPI(Resource):

    @api.doc(parser=parser)
    @api.marshal_with(resource_fields)
    def get(self):
        args = parser.parse_args()        
        prediction = usedCarPricesPredict(args['Year'], args['Mileage'], args['State'], args['Make'], args['Model'])
        return {"result": prediction[0]}, 200


# Ejecución de la aplicación que disponibiliza el modelo de manera local en el puerto 5000
app.run(debug=True, use_reloader=False, host='0.0.0.0', port=88)
